#! /bin/sh

echo "Checking Assignment 3 Solutions" > results.txt

echo "" >> results.txt

echo "======= Generating query output =======" >> results.txt

# checking queries
for query in q1 q2 q3 q4 q5 q6 q7
do
   echo "" >> results.txt
   echo "--- Query" $query "---" >> results.txt
   echo "" >> results.txt
   echo "Raw results:" >> results.txt
   galax-run $query.xq >> results.txt 2>&1
done


echo "" >> results.txt
echo "======= Validating xml generated by query q7 =======" >> results.txt

echo "" >> results.txt
echo "--- Query" q7 "---" >> results.txt
echo "<?xml version='1.0' standalone='no' ?>" > TEMP.xml
echo "<!DOCTYPE Stats SYSTEM 'stats.dtd'>" >> TEMP.xml
galax-run q7.xq >> TEMP.xml  2>&1
echo "Results well-formed?" >> results.txt
xmllint --format TEMP.xml >> results.txt  2>&1
echo "" >> results.txt
echo "Results valid?" >> results.txt
xmllint --noout --format --dtdvalid stats.dtd TEMP.xml >> results.txt

